# Autogenerated by `cargo run website-data` in https://github.com/rust-lang/team
governance-team-wg-self-profile-name = Self-Profile
governance-team-wg-rfc-2229-name = RFC 2229
governance-team-wg-nll-name = Non-Lexical Lifetimes (NLL)
governance-team-mods-discourse-description = Модерирование users.rust-lang.org и internals.rust-lang.org
governance-team-community-name = Community team
governance-team-mods-name = Moderation team
governance-team-wg-parallel-rustc-name = Parallel rustc
governance-team-wg-async-await-description = Реализация async-await
governance-team-core-name = Core team
governance-team-wg-llvm-name = LLVM
governance-team-wg-meta-name = Meta
governance-team-mods-discord-name = Модераторы Discord
governance-team-clippy-name = Clippy
governance-team-wg-traits-name = Traits
governance-team-wg-rls-2-name = RLS 2.0
governance-team-wg-polonius-name = Polonius
