# Autogenerated by `cargo run dump-website` in https://github.com/rust-lang/team
governance-team-wg-nll-name = NLL 팀
governance-team-wg-nll-description = 새로운 MIR 기반 차용 검사기 및 비어휘 수명 구현

governance-team-community-survey-name = 조사 팀
governance-team-community-survey-description = 커뮤니티 설문 조사 실행, 분석 및 발표

governance-team-ides-name = IDE 및 에디터 팀
governance-team-ides-description = IDE, 에디터 및 레이서나 RLS와 같은 기타 도구 개발

governance-team-wg-rustfix-name = 러스트 픽스 팀
governance-team-wg-rustfix-description = 카고 픽스 개발 및 타 개발 팀의 연락 지점 역할 수행

governance-team-wg-security-response-name = 보안 응답 팀
governance-team-wg-security-response-description = 들어오는 취약점 보고서 트리밍 및 응답

governance-team-clippy-name = 클리피 팀
governance-team-clippy-description = 클리피 린터 설계 및 구현

governance-team-miri-name = 미리
governance-team-miri-description = 미리(Miri) 인터프리터 설계 및 구현

governance-team-wg-debugging-name = 디버깅 팀
governance-team-wg-debugging-description = 러스트 디버깅 툴 개발 및 관리

governance-team-compiler-name = 컴파일러 팀
governance-team-compiler-description = 컴파일러 내부 및 최적화 개발 및 관리

governance-team-core-name = 코어 팀
governance-team-core-description = 러스트의 전반적인 방향, 하위 팀 리더십 및 크로스 커팅 문제 관리

governance-team-wg-traits-name = 트레이트 팀
governance-team-wg-traits-description = 초크 접근 방식을 따르도록 러스트 특성 구현 및 수정

governance-team-wg-parallel-rustc-name = 병행 러스트씨 팀
governance-team-wg-parallel-rustc-description = 러스트씨를 위한 병행 컴파일을 기본값으로 설정

governance-team-wg-cli-name = CLI 팀
governance-team-wg-cli-description = 러스트에서 크고 작은 터미널 앱을 쓰는 엔드 투 엔드 경험에 초점

governance-team-mods-discord-name = 디스코드 중재 팀
governance-team-mods-discord-description = 디스코드 서버 중재

governance-team-wg-compiler-performance-name = 컴파일러 퍼포먼스 팀
governance-team-wg-compiler-performance-description = 러스트씨 컴파일러 성능 (빌드 시간) 향상

governance-team-community-content-name = 컨텐츠 팀
governance-team-community-content-description = 커뮤니티 컨텐츠 수집 및 개발

governance-team-wg-async-foundations-name = 비동기 파운데이션 팀
governance-team-wg-async-foundations-description = 비동기화를 위한 핵심 언어 및 라이브러리 지원 추구

governance-team-wg-gamedev-name = 게임 개발 팀
governance-team-wg-gamedev-description = 러스트를 게임 개발의 기본 선택으로 만드는 것에 초점

governance-team-wg-llvm-name = LLVM 팀
governance-team-wg-llvm-description = LLVM 업스트림과 협력하여 개발 시 러스트 표시

governance-team-community-rustbridge-name = 러스트 브릿지 팀
governance-team-community-rustbridge-description = 대표성이 낮은 그룹을 러스트에 포함시키도록 도움

governance-team-wg-grammar-name = 문법 팀
governance-team-wg-grammar-description = 러스트에 대한 공식 문법 작성 및 기존 구현에 대한 검증

governance-team-lang-name = 언어 팀
governance-team-lang-description = 새로운 언어 기능의 설계 및 구현 지원

governance-team-docs-rs-name = Docs.rs 팀
governance-team-docs-rs-description = 크레이트용 문서 호스팅 서비스

governance-team-wg-pgo-name = 프로필 유도 최적화 팀
governance-team-wg-pgo-description = 러스트를 위한 프로필 유도 최적화 구현

governance-team-rustdoc-name = 러스트독 팀
governance-team-rustdoc-description = 러스트독 및 Docs.rs를 포함한 문서 도구 개발 및 관리

governance-team-wg-secure-code-name = 보안 코드 팀
governance-team-wg-secure-code-description = 러스트에 보안 코드 작성을 용이하도록 도움

governance-team-release-name = 릴리즈 팀
governance-team-release-description = 퇴행 및 안전화 추적 및 러스트 릴리즈 배

governance-team-wg-wasm-name = WASM 팀
governance-team-wg-wasm-description = 웹 어셈블리를 통해 자바스크립트 라이브러리 및 앱에 러스트 코드를 내장하는 엔드 투 엔드 경험 개선

governance-team-wg-learning-name = 러닝 팀
governance-team-wg-learning-description = 컴파일러 가이드 및 API 설명서가 업데이트 되었는지 확인하여 컴파일러를 쉽게 학습하도록 도움

governance-team-libs-name = 라이브러리 팀
governance-team-libs-description = 러스트 표준 라이브러리, 공식 러스트 크레이트, 코드 컨벤션 및 생태계 지원 개발 및 관리

governance-team-wg-triage-name = 트라이어지 팀
governance-team-wg-triage-description = 러스트 언어 하에 리포지토리 트라이어징

governance-team-crates-io-name = Crates.io 팀
governance-team-crates-io-description = crates.io에 대한 운영, 개발 및 공식 정책 관리

governance-team-reference-name = 레퍼런스 팀
governance-team-reference-description = 러스트 레퍼런스 개발 및 작성

governance-team-wg-safe-transmute-name = 안전한 뮤테이팅 팀
governance-team-wg-safe-transmute-description = 타입 간 안전한 뮤테이팅을 지원하기 위한 러스트 언어를 확장

governance-team-core-observers-name = 코어 팀 감시자
governance-team-core-observers-description = 코어 팀 감시

governance-team-wg-ffi-unwind-name = ffi-unwind 팀
governance-team-wg-ffi-unwind-description = FFI 경계를 넘는 풀링을 지원하기 위해 러스트 언어를 확장

governance-team-community-events-name = 이벤트 팀
governance-team-community-events-description = 커뮤니티 이벤트 지원 및 조직

governance-team-devtools-name = 개발 툴 팀
governance-team-devtools-description = 러스트 개발 도구 지원 및 생성

governance-team-wg-bindgen-name = Bindgen 팀
governance-team-wg-bindgen-description = FFI 바인딩 생성 도구 개발

governance-team-docs-name = 문서화 팀
governance-team-docs-description = 러스트 문서 품질 향상 및 완화

governance-team-mods-name = 절제 팀
governance-team-mods-description = 행동 강령 및 커뮤니티 표준을 준수하도록 지원

governance-team-wg-embedded-name = 임베디드 장치 팀
governance-team-wg-embedded-description = 리소스 제약 환경 및 비전통 플랫폼에서 러스트를 사용하는 엔드 투 엔드 환경 개선

governance-team-cargo-name = 카고 팀
governance-team-cargo-description = 공식 러스트 패키지 매니저인 카고 설계 및 구현

governance-team-operations-name = 작전 팀
governance-team-operations-description = 릴리즈, 봇, 인프라 등을 관리

governance-team-wg-meta-name = 메타 팀
governance-team-wg-meta-description = 러스트 컴파일러 팀 구성 및 관리

governance-team-mods-discourse-name = 디스코스 절제 팀
governance-team-mods-discourse-description = users.rust-lang.org과 internals.rust-lang.org 중재

governance-team-infra-name = 인프라 팀
governance-team-infra-description = CI, 릴리즈, 봇 및 메트릭스를 포함하여 러스트 프로젝트 자체를 지원하는 인프라 관

governance-team-wg-governance-name = 거버넌스 팀
governance-team-wg-governance-description = 러스트 팀 거버넌스 관리 및 개선

governance-team-wg-unsafe-code-guidelines-name = UCG 팀
governance-team-wg-unsafe-code-guidelines-description = 안전하지 않은 코드의 어떤 종류의 동작이 안전하지 않은지 정의하는 "Unsafe Code Guidelines" 작성

governance-team-wg-rfc-2229-name = RFC 2229 팀
governance-team-wg-rfc-2229-description = 클로저 캡쳐의 동작 개선 및 클로저에 대한 문서 개선

governance-team-wg-mir-opt-name = MIR 최적화 팀
governance-team-wg-mir-opt-description = MIR 최적화 작성 및 MIR 재조정 최적화

governance-team-rust-by-example-name = 예제로 보는 러스트 팀
governance-team-rust-by-example-description = 러스트 공식 서적 "예제로 보는 러스트" 유지 및 업데이트

governance-team-community-name = 커뮤니티 팀
governance-team-community-description = 이벤트, 컨텐츠 작성 및 러스트 브릿지 프로그램 조정 및 지원, 커뮤니티 조사 실시

governance-team-wg-rustup-name = 러스트업 팀
governance-team-wg-rustup-description = 러스트업 설계 및 구현

governance-team-wg-rustfmt-name = 러스트포맷 팀
governance-team-wg-rustfmt-description = 러스트 코드의 포맷 도구인 러스트포맷(rustfmt) 설계 및 구현

governance-team-compiler-contributors-name = 컴파일러 팀 기여자
governance-team-compiler-contributors-description = 정기적으로 러스트 컴파일러에 기여하는 사람들

governance-team-community-localization-name = 현지화 팀
governance-team-community-localization-description = 컴파일러, 문서 및 웹 사이트의 현지화 작업

governance-team-alumni-name = 러스트 동문
governance-team-alumni-description = 은퇴 후 여가를 즐기는 사람들

governance-team-wg-self-profile-name = 자체 프로필 팀
governance-team-wg-self-profile-description = 러스트 컴파일러의 -Z 자체 프로필 기능 개선

governance-team-wg-embedded-resources-name = 임베디드 리소스 팀
governance-team-wg-embedded-resources-description = 포함된 작업 그룹이 소유한 다양한 리소스 관리

governance-team-wg-rls-2-name = RLS 2.0 팀
governance-team-wg-rls-2-description = IDE에 맞춘 새로운 컴파일러 아키텍처로 실험

governance-team-wg-polonius-name = 폴로니우스 팀
governance-team-wg-polonius-description = 실험적인 새로운 새 바로우 체커 구현 작업

