# Autogenerated by `cargo run website-data` in https://github.com/rust-lang/team
governance-team-lang-name = Language team
governance-team-lang-description = designing new language features

governance-team-rustdoc-name = Rustdoc team
governance-team-rustdoc-description = Documentation tools including Rustdoc and docs.rs

governance-team-mods-name = Moderation team
governance-team-mods-description = helping uphold the code of conduct

governance-team-wg-localization-name = Localization WG
governance-team-wg-localization-description = Working towards

governance-team-mods-discord-name = Discord moderators
governance-team-mods-discord-description = Moderating the Discord server

governance-team-mods-discourse-name = Discourse moderators
governance-team-mods-discourse-description = Moderating users.rust-lang.org and internals.rust-lang.org

governance-team-wg-rustfix-name = Rustfix working group
governance-team-wg-rustfix-description = Improve cargo-fix and be a point of contact for other teams

governance-team-wg-net-embedded-name = Embedded networking group
governance-team-wg-net-embedded-description = Our goal is to support IoT development.

governance-team-wg-rls-2-name = RLS 2.0
governance-team-wg-rls-2-description = Experimenting with a new compiler architecture tailored for IDEs

governance-team-wg-compiler-performance-name = Compiler Performance
governance-team-wg-compiler-performance-description = Improving rustc compilation performance (build times).

governance-team-wg-net-name = Networking working group
governance-team-wg-net-description = Focusing on the end-to-end experience for both sync and async networking code, in coordination with the growing ecosystem in this space.

governance-team-wg-bindgen-name = Bindgen working group
governance-team-wg-bindgen-description = tools for generating FFI bindings

governance-team-wg-embedded-name = Embedded devices working group
governance-team-wg-embedded-description = Focusing on the end-to-end experience of using Rust in resource-constrained environments and non-traditional platforms.

governance-team-wg-net-async-name = Async foundations working group
governance-team-wg-net-async-description = Our goal is to bring async/await onto a path to stabilization and to provide documentation for asynchronous programming.

governance-team-wg-net-web-name = Web foundations working group
governance-team-wg-net-web-description = Our goal is to improve web programming in Rust.

governance-team-wg-pgo-name = Profile-guided optimization
governance-team-wg-pgo-description = Implementing profile-guided optimization for rustc

governance-team-operations-name = Operations team
governance-team-operations-description = Handling releases, bots, infra, and more.

governance-team-alumni-name = Rust team alumni
governance-team-alumni-description = enjoying a leisurely retirement

governance-team-rust-by-example-name = Rust by Example team
governance-team-rust-by-example-description = maintaining and updating Rust By Example

governance-team-wg-async-await-name = Async-await Implementation
governance-team-wg-async-await-description = Implementing async-await

governance-team-wg-wasm-name = WebAssembly (WASM) working group
governance-team-wg-wasm-description = Focusing on the end-to-end experience of embedding Rust code in JS libraries and apps via WebAssembly.

governance-team-cargo-name = Cargo team
governance-team-cargo-description = design and implementation of Cargo

governance-team-wg-traits-name = Traits
governance-team-wg-traits-description = Revamping the rustc trait implementation to follow the Chalk approach.

governance-team-core-name = Core team
governance-team-core-description = Direction of the project, subteam leadership, cross-cutting concerns.

governance-team-wg-rustfmt-name = Rustfmt working group
governance-team-wg-rustfmt-description = design and implementation of Rustfmt

governance-team-docs-name = Documentation team
governance-team-docs-description = ensuring Rust has fantastic documentation

governance-team-wg-rfc-2229-name = RFC 2229
governance-team-wg-rfc-2229-description = Make a closure capture individual fields of the variable rather than the entire composite variable

governance-team-wg-meta-name = Meta
governance-team-wg-meta-description = How compiler team organizes itself

governance-team-wg-parallel-rustc-name = Parallel rustc
governance-team-wg-parallel-rustc-description = Making parallel compilation the default for rustc

governance-team-infra-name = Infrastructure team
governance-team-infra-description = infrastructure supporting the Rust project itself: CI, releases, bots, metrics

governance-team-wg-nll-name = Non-Lexical Lifetimes (NLL)
governance-team-wg-nll-description = Implementing the new MIR-based borrow check and non-lexical lifetimes

governance-team-compiler-name = Compiler team
governance-team-compiler-description = compiler internals, optimizations

governance-team-community-events-name = Events team
governance-team-community-events-description = Supporting community events with knowledge and resources.

governance-team-community-rustbridge-name = RustBridge team
governance-team-community-rustbridge-description = An inclusive educational initiative focused on bringing underrepresented groups into Rust.

governance-team-wg-grammar-name = Grammar
governance-team-wg-grammar-description = Working out a the official, formal grammar for Rust and validating it against existing implementations.

governance-team-wg-llvm-name = LLVM
governance-team-wg-llvm-description = Working with LLVM upstream to represent Rust in its development

governance-team-wg-mir-opt-name = MIR Optimizations
governance-team-wg-mir-opt-description = Write MIR optimizations and refactor the MIR to be more optimizable.

governance-team-core-observers-name = Core Team Observers
governance-team-core-observers-description = observers on the core team

governance-team-wg-cli-name = Command-line interfaces (CLI) working group
governance-team-wg-cli-description = Focusing on the end-to-end experience of writing CLI apps, both large and small, in Rust.

governance-team-wg-learning-name = Learning
governance-team-wg-learning-description = Make the compiler easier to learn by ensuring that rustc-guide and api docs are 'complete'

governance-team-wg-debugging-name = Debugging working group
governance-team-wg-debugging-description = debugging tools and foundations

governance-team-community-survey-name = Survey team
governance-team-community-survey-description = Running, analysing, and presenting the community survey.

governance-team-community-name = Community team
governance-team-community-description = Coordination and supporting events, content creation, running the RustBridge program, and conducting the survey.

governance-team-crates-io-name = Crates.io team
governance-team-crates-io-description = Management of operations, development, and policies for crates.io.

governance-team-ides-name = IDEs and editors team
governance-team-ides-description = IDEs, editors, and supporting tools such as Racer and the RLS

governance-team-reference-name = Reference team
governance-team-reference-description = working on the rust reference

governance-team-wg-rustup-name = Rustup working group
governance-team-wg-rustup-description = design and implementation of Rustup

governance-team-wg-unsafe-code-guidelines-name = Unsafe Code Guidelines (UCG)
governance-team-wg-unsafe-code-guidelines-description = Working out the "Unsafe Code Guidelines", which define what kind of behavior unsafe code can and cannot do.

governance-team-libs-name = Library team
governance-team-libs-description = the Rust standard library, rust-lang crates, conventions, and ecosystem support

governance-team-wg-governance-name = Governance Working Group
governance-team-wg-governance-description = Working on improving Rust Governance

governance-team-release-name = Release team
governance-team-release-description = tracking regressions, stabilizations, and producing Rust releases

governance-team-wg-self-profile-name = Self-Profile
governance-team-wg-self-profile-description = Improving the -Z self-profile feature

governance-team-devtools-name = Dev tools team
governance-team-devtools-description = Rust developer tools

governance-team-clippy-name = Clippy
governance-team-clippy-description = design and implementation of the Clippy linter

governance-team-community-content-name = Content team
governance-team-community-content-description = Helping support community content collection and development.

