# Autogenerated by `cargo run dump-website` in https://github.com/rust-lang/team
governance-team-wg-nll-name = Non-Lexical Lifetimes (NLL) working group
governance-team-wg-nll-description = Implementing the new MIR-based borrow checker and non-lexical lifetimes in Rust

governance-team-community-survey-name = Survey team
governance-team-community-survey-description = Running, analysing, and presenting the community survey

governance-team-ides-name = IDEs and editors team
governance-team-ides-description = Developing IDEs, editors, and other development tools such as Racer and the RLS

governance-team-wg-rustfix-name = Rustfix working group
governance-team-wg-rustfix-description = Developing cargo-fix and serving as a point of contact for other teams

governance-team-wg-security-response-name = Security Response WG
governance-team-wg-security-response-description = Triaging and responding to incoming vulnerability reports

governance-team-clippy-name = Clippy team
governance-team-clippy-description = Designing and implementing the Clippy linter

governance-team-miri-name = Miri
governance-team-miri-description = design and implementation of the Miri interpreter

governance-team-wg-debugging-name = Debugging working group
governance-team-wg-debugging-description = Developing and managing Rust debugging tools

governance-team-compiler-name = Compiler team
governance-team-compiler-description = Developing and managing compiler internals and optimizations

governance-team-core-name = Core team
governance-team-core-description = Managing the overall direction of Rust, subteam leadership, and any cross-cutting issues

governance-team-wg-traits-name = Traits working group
governance-team-wg-traits-description = Revamping the rustc trait implementation to follow the Chalk approach

governance-team-wg-parallel-rustc-name = Parallel rustc working group
governance-team-wg-parallel-rustc-description = Making parallel compilation the default for rustc

governance-team-wg-cli-name = Command-line interfaces (CLI) working group
governance-team-wg-cli-description = Focusing on the end-to-end experience of writing terminal apps, both large and small, in Rust.

governance-team-mods-discord-name = Discord moderators
governance-team-mods-discord-description = Moderating the Discord server

governance-team-wg-compiler-performance-name = Compiler performance working group
governance-team-wg-compiler-performance-description = Improving rustc compilation performance (build times)

governance-team-community-content-name = Content team
governance-team-community-content-description = Collecting and developing community content

governance-team-wg-async-foundations-name = Async Foundations working group
governance-team-wg-async-foundations-description = Pursuing core language and library support for async-await

governance-team-wg-gamedev-name = Game development working group
governance-team-wg-gamedev-description = Focusing on making Rust the default choice for game development.

governance-team-wg-llvm-name = LLVM working group
governance-team-wg-llvm-description = Working with LLVM upstream to represent Rust in its development

governance-team-community-rustbridge-name = RustBridge team
governance-team-community-rustbridge-description = Helping to bring underrepresented groups into Rust

governance-team-wg-grammar-name = Grammar working group
governance-team-wg-grammar-description = Working out the official, formal grammar for Rust and validating it against existing implementations

governance-team-lang-name = Language team
governance-team-lang-description = Designing and helping to implement new language features

governance-team-docs-rs-name = Docs.rs team
governance-team-docs-rs-description = Docs.rs, the documentation hosting service for crates

governance-team-wg-pgo-name = Profile-guided optimization working group
governance-team-wg-pgo-description = Implementing profile-guided optimization for rustc

governance-team-rustdoc-name = Rustdoc team
governance-team-rustdoc-description = Developing and managing documentation tools, including Rustdoc and docs.rs

governance-team-wg-secure-code-name = Secure Code working group
governance-team-wg-secure-code-description = Making it easy to write secure code in Rust

governance-team-release-name = Release team
governance-team-release-description = Tracking regressions and stabilizations, and producing Rust releases

governance-team-wg-wasm-name = WebAssembly (WASM) working group
governance-team-wg-wasm-description = Improving on the end-to-end experience of embedding Rust code in JS libraries and apps via WebAssembly

governance-team-wg-rustc-dev-guide-name = Rustc Dev Guide working group
governance-team-wg-rustc-dev-guide-description = Making the compiler easier to learn by ensuring that the compiler guide and API documentation are updated

governance-team-libs-name = Library team
governance-team-libs-description = Developing and managing the Rust standard library, official rust-lang crates, code conventions, and ecosystem support

governance-team-wg-triage-name = Triage working group
governance-team-wg-triage-description = Triaging repositories under the rust-lang organisation

governance-team-crates-io-name = Crates.io team
governance-team-crates-io-description = Managing operations, development, and official policies for crates.io

governance-team-reference-name = Reference team
governance-team-reference-description = Developing and writing the Rust reference

governance-team-wg-safe-transmute-name = safe-transmute project group
governance-team-wg-safe-transmute-description = A working-group project to extend the Rust language to support safe transmute between types

governance-team-core-observers-name = Core team observers
governance-team-core-observers-description = Observers on the core team

governance-team-wg-ffi-unwind-name = ffi-unwind project group
governance-team-wg-ffi-unwind-description = A working-group project to extend the Rust language to support unwinding that crosses FFI boundaries

governance-team-community-events-name = Events team
governance-team-community-events-description = Supporting and organizing community events

governance-team-devtools-name = Dev tools team
governance-team-devtools-description = Contributing to and creating the Rust development tools

governance-team-wg-bindgen-name = Bindgen working group
governance-team-wg-bindgen-description = Developing tools for generating FFI bindings

governance-team-docs-name = Documentation team
governance-team-docs-description = Improving and moderating the quality of Rust's documentation

governance-team-mods-name = Moderation team
governance-team-mods-description = Helping uphold the code of conduct and community standards

governance-team-wg-embedded-name = Embedded devices working group
governance-team-wg-embedded-description = Focusing on improving the end-to-end experience of using Rust in resource-constrained environments and non-traditional platforms

governance-team-cargo-name = Cargo team
governance-team-cargo-description = Designing and implementing the official Rust package manager, Cargo

governance-team-operations-name = Operations team
governance-team-operations-description = Handling releases, bots, infra, and more

governance-team-wg-meta-name = Meta working group
governance-team-wg-meta-description = Organizing and managing the Rust compiler team

governance-team-mods-discourse-name = Discourse moderators
governance-team-mods-discourse-description = Moderating users.rust-lang.org and internals.rust-lang.org

governance-team-infra-name = Infrastructure team
governance-team-infra-description = Managing the infrastructure supporting the Rust project itself, including CI, releases, bots, and metrics

governance-team-wg-governance-name = Governance working group
governance-team-wg-governance-description = Managing and improving Rust team governance

governance-team-wg-unsafe-code-guidelines-name = Unsafe Code Guidelines (UCG) working group
governance-team-wg-unsafe-code-guidelines-description = Working out the "Unsafe Code Guidelines", which define what kind of behavior unsafe code can and cannot do

governance-team-wg-rfc-2229-name = RFC 2229 working group
governance-team-wg-rfc-2229-description = Improving the behavior of closure-capture, and improving the documentation on closures

governance-team-wg-mir-opt-name = MIR optimizations working group
governance-team-wg-mir-opt-description = Writing MIR optimizations and refactoring the MIR to be more optimizable

governance-team-rust-by-example-name = Rust by Example team
governance-team-rust-by-example-description = Maintaining and updating an official Rust book, Rust By Example

governance-team-community-name = Community team
governance-team-community-description = Coordinating and supporting events, content creation, and the RustBridge program, as well as conducting community surveys

governance-team-wg-rustup-name = Rustup working group
governance-team-wg-rustup-description = Designing and implementing rustup

governance-team-wg-rustfmt-name = Rustfmt working group
governance-team-wg-rustfmt-description = Designing and implementing rustfmt, a formatting tool for Rust code

governance-team-compiler-contributors-name = Compiler team contributors
governance-team-compiler-contributors-description = Folks who contribute to the Rust compiler on a regular basis

governance-team-community-localization-name = Localization team
governance-team-community-localization-description = Working on localization of compiler, documentation and websites

governance-team-alumni-name = Rust team alumni
governance-team-alumni-description = Enjoying a leisurely retirement

governance-team-wg-self-profile-name = Self-profile working group
governance-team-wg-self-profile-description = Improving the -Z self-profile feature of the Rust compiler

governance-team-wg-embedded-resources-name = Embedded resources working group
governance-team-wg-embedded-resources-description = Managing various resources owned by the embedded working group

governance-team-wg-rls-2-name = RLS 2.0 working group
governance-team-wg-rls-2-description = Experimenting with a new compiler architecture tailored for IDEs

governance-team-wg-polonius-name = Polonius working group
governance-team-wg-polonius-description = Working on an experimental new borrow-checker implementation

