# Autogenerated by `cargo run dump-website` in https://github.com/rust-lang/team
governance-team-alumni-name = Rust team alumni
governance-team-alumni-description = Enjoying a leisurely retirement

governance-team-bootstrap-name = Bootstrap team
governance-team-bootstrap-description = Maintaining and improving the build system for rust-lang/rust

governance-team-cargo-name = Cargo team
governance-team-cargo-description = Designing and implementing the official Rust package manager, Cargo

governance-team-clippy-name = Clippy team
governance-team-clippy-description = Designing and implementing the Clippy linter

governance-team-community-content-name = Content team
governance-team-community-content-description = Collecting and developing community content

governance-team-community-events-name = Events team
governance-team-community-events-description = Supporting and organizing community events

governance-team-community-localization-name = Localization team
governance-team-community-localization-description = Working on localization of compiler, documentation and websites

governance-team-community-rustbridge-name = RustBridge team
governance-team-community-rustbridge-description = Helping to bring underrepresented groups into Rust

governance-team-community-survey-name = Survey team
governance-team-community-survey-description = Running, analysing, and presenting the community survey

governance-team-compiler-name = Compiler team
governance-team-compiler-description = Developing and managing compiler internals and optimizations

governance-team-compiler-contributors-name = Compiler team contributors
governance-team-compiler-contributors-description = Contributing to the Rust compiler on a regular basis

governance-team-crate-maintainers-name = Crate maintainers
governance-team-crate-maintainers-description = Maintaining official rust-lang crates such as log, libc, cc, and more.

governance-team-crates-io-name = Crates.io team
governance-team-crates-io-description = Managing operations, development, and official policies for crates.io

governance-team-devtools-name = Dev tools team
governance-team-devtools-description = Contributing to and creating the Rust development tools

governance-team-docs-rs-name = Docs.rs team
governance-team-docs-rs-description = Docs.rs, the documentation hosting service for crates

governance-team-ides-name = IDEs and editors team
governance-team-ides-description = Developing IDEs, editors, and other development tools such as Racer and rust-analyzer

governance-team-infra-name = Infrastructure team
governance-team-infra-description = Managing the infrastructure supporting the Rust project itself, including CI, releases, bots, and metrics

governance-team-lang-name = Language team
governance-team-lang-description = Designing and helping to implement new language features

governance-team-lang-advisors-name = Language Advisors team
governance-team-lang-advisors-description = Advising on the development of the Rust language

governance-team-lang-docs-name = lang-docs team
governance-team-lang-docs-description = Developing and writing the docs related to the lang team

governance-team-leadership-council-name = Leadership council
governance-team-leadership-council-description = Charged with the success of the Rust Project as whole, consisting of representatives from top-level teams

governance-team-libs-name = Library team
governance-team-libs-description = Managing and maintaining the Rust standard library and official rust-lang crates

governance-team-libs-api-name = Library API team
governance-team-libs-api-description = Designing and maintaining the standard library API and guarding its stability

governance-team-libs-contributors-name = Library contributors
governance-team-libs-contributors-description = Contributing to the Rust standard library on a regular basis

governance-team-miri-name = Miri
governance-team-miri-description = Designing and implementing the Miri interpreter

governance-team-mods-name = Moderation team
governance-team-mods-description = Helping uphold the code of conduct and community standards

governance-team-mods-discord-name = Discord moderators
governance-team-mods-discord-description = Moderating the Discord server

governance-team-mods-discourse-name = Discourse moderators
governance-team-mods-discourse-description = Moderating users.rust-lang.org and internals.rust-lang.org

governance-team-opsem-name = Operational Semantics team
governance-team-opsem-description = Working on deciding and specifying the semantics of Rust around unsafe code

governance-team-project-async-crashdump-debugging-name = Async Crashdump Debugging Initiative
governance-team-project-async-crashdump-debugging-description = Simplify crashdump debugging of async programs

governance-team-project-const-generics-name = Const Generics Project Group
governance-team-project-const-generics-description = Working to advance const generics support in the Rust language

governance-team-project-dyn-upcasting-name = Dyn Upcasting Initiative
governance-team-project-dyn-upcasting-description = Allowing Upcasting between trait objects

governance-team-project-edition-2021-name = Edition 2021 Project Group
governance-team-project-edition-2021-description = Managing the Rust 2021 edition

governance-team-project-error-handling-name = Error Handling Project Group
governance-team-project-error-handling-description = Identifying error handling best practices and consolidating the ecosystem

governance-team-project-exploit-mitigations-name = Exploit Mitigations Project Group
governance-team-project-exploit-mitigations-description = Maintaining and improving the existing, implementing, and researching new exploit mitigations for the Rust compiler

governance-team-project-generic-associated-types-name = Generic Associated Types Initiative
governance-team-project-generic-associated-types-description = Extending Rust with Generic Associated Types

governance-team-project-impl-trait-name = Impl Trait Initiative
governance-team-project-impl-trait-description = Extending Rust with Impl Trait

governance-team-project-keyword-generics-name = Keyword Generics Initiative
governance-team-project-keyword-generics-description = Extending the type system to support keyword generics

governance-team-project-negative-impls-name = Negative Impls Initiative
governance-team-project-negative-impls-description = Extending negative impls and integrating them into coherence

governance-team-project-portable-simd-name = Portable SIMD Project Group
governance-team-project-portable-simd-description = Adding portable SIMD to the standard library

governance-team-project-stable-mir-name = Stable MIR Project Group
governance-team-project-stable-mir-description = Define compiler intermediate representation usable by external tools

governance-team-project-thir-unsafeck-name = THIR Unsafety Checker Project Group
governance-team-project-thir-unsafeck-description = Working on refactoring unsafety checking to operate on THIR

governance-team-project-trait-system-refactor-name = Rustc Trait System Refactor Initiative
governance-team-project-trait-system-refactor-description = Refactoring the trait system of rustc

governance-team-regex-name = Regex crate team
governance-team-regex-description = Developing and maintaining the regex crate

governance-team-release-name = Release team
governance-team-release-description = Tracking regressions and stabilizations, and producing Rust releases

governance-team-rust-analyzer-name = rust-analyzer team
governance-team-rust-analyzer-description = Rust IDE support and error-resilient compiler front-end

governance-team-rustdoc-name = Rustdoc team
governance-team-rustdoc-description = Developing and managing the Rustdoc documentation tool

governance-team-rustfmt-name = Rustfmt team
governance-team-rustfmt-description = Designing and implementing rustfmt, a formatting tool for Rust code

governance-team-rustup-name = Rustup team
governance-team-rustup-description = Designing and implementing rustup

governance-team-style-name = Style team
governance-team-style-description = Defining and evolving the default Rust coding style

governance-team-triagebot-name = Triagebot team
governance-team-triagebot-description = Maintaining and improving the rust-lang/triagebot tooling

governance-team-types-name = Types team
governance-team-types-description = Working to implement and formally define the semantics of the Rust language

governance-team-wg-allocators-name = Allocator working group
governance-team-wg-allocators-description = Paving a path for a standard set of allocator traits to be used in collections

governance-team-wg-async-name = Async working group
governance-team-wg-async-description = Pursuing core language and library support for async-await

governance-team-wg-bindgen-name = Bindgen working group
governance-team-wg-bindgen-description = Developing tools for generating FFI bindings

governance-team-wg-cli-name = Command-line interfaces (CLI) working group
governance-team-wg-cli-description = Focusing on the end-to-end experience of writing terminal apps, both large and small, in Rust.

governance-team-wg-compiler-performance-name = Compiler performance working group
governance-team-wg-compiler-performance-description = Improving rustc compilation performance (build times)

governance-team-wg-const-eval-name = Compile-time Function Evaluation Working Group
governance-team-wg-const-eval-description = Soundly expanding the capabilities of compile-time function evaluation in Rust

governance-team-wg-debugging-name = Debugging Working Group
governance-team-wg-debugging-description = Providing users with a great experience when debugging Rust code

governance-team-wg-diagnostics-name = Diagnostics working group
governance-team-wg-diagnostics-description = Aiming to make rustc better at telling the user why the compiler isn't smart enough to understand their code yet

governance-team-wg-embedded-name = Embedded devices working group
governance-team-wg-embedded-description = Focusing on improving the end-to-end experience of using Rust in resource-constrained environments and non-traditional platforms

governance-team-wg-embedded-core-name = Embedded core team
governance-team-wg-embedded-core-description = The core team represents the WG in meetings with the Rust teams

governance-team-wg-embedded-cortex-a-name = Embedded Cortex-A team
governance-team-wg-embedded-cortex-a-description = Develops and maintains the core of the Cortex-A crate ecosystem

governance-team-wg-embedded-cortex-m-name = Embedded Cortex-M team
governance-team-wg-embedded-cortex-m-description = Develops and maintains the core of the Cortex-M crate ecosystem

governance-team-wg-embedded-cortex-r-name = Embedded Cortex-R team
governance-team-wg-embedded-cortex-r-description = Develops and maintains the core of the Cortex-R crate ecosystem

governance-team-wg-embedded-hal-name = Embedded HAL team
governance-team-wg-embedded-hal-description = Develops and maintains crates that ease the development of Hardware Abstraction Layers, Board Support Crates and drivers

governance-team-wg-embedded-infra-name = Embedded infrastructure team
governance-team-wg-embedded-infra-description = Managing infrastructure for wg-embedded

governance-team-wg-embedded-linux-name = Embedded Linux team
governance-team-wg-embedded-linux-description = The embedded Linux team develops and maintains the core of the embedded Linux crate ecosystem.

governance-team-wg-embedded-msp430-name = Embedded MSP430 team
governance-team-wg-embedded-msp430-description = Develops and maintains the core of the embedded MSP430 crate ecosystem

governance-team-wg-embedded-resources-name = Embedded resources working group
governance-team-wg-embedded-resources-description = Managing various resources owned by the embedded working group

governance-team-wg-embedded-riscv-name = Embedded RISCV team
governance-team-wg-embedded-riscv-description = Develops and maintains the core of the embedded RISCV crate ecosystem

governance-team-wg-embedded-tools-name = Embedded Tools Team
governance-team-wg-embedded-tools-description = Develops and maintains core embedded tools

governance-team-wg-embedded-triage-name = Embedded Triage Team
governance-team-wg-embedded-triage-description = The triage team keeps PR queues moving; they ensure no PR is left unattended

governance-team-wg-ffi-unwind-name = ffi-unwind project group
governance-team-wg-ffi-unwind-description = A working-group project to extend the Rust language to support unwinding that crosses FFI boundaries

governance-team-wg-gamedev-name = Game development working group
governance-team-wg-gamedev-description = Focusing on making Rust the default choice for game development

governance-team-wg-grammar-name = Grammar working group
governance-team-wg-grammar-description = Working out the official, formal grammar for Rust and validating it against existing implementations

governance-team-wg-incr-comp-name = Incremental compilation working group
governance-team-wg-incr-comp-description = Improving incremental compilation in rustc

governance-team-wg-inline-asm-name = inline-asm project group
governance-team-wg-inline-asm-description = A working-group project to extend the Rust language to support inline assembly

governance-team-wg-llvm-name = LLVM working group
governance-team-wg-llvm-description = Working with LLVM upstream to represent Rust in its development

governance-team-wg-mir-opt-name = MIR optimizations working group
governance-team-wg-mir-opt-description = Writing MIR optimizations and refactoring the MIR to be more optimizable

governance-team-wg-parallel-rustc-name = Parallel rustc working group
governance-team-wg-parallel-rustc-description = Making parallel compilation the default for rustc

governance-team-wg-parselib-name = Parselib working group
governance-team-wg-parselib-description = Sharing the parser between rustc and rust-analyzer

governance-team-wg-pgo-name = Profile-guided optimization working group
governance-team-wg-pgo-description = Implementing profile-guided optimization for rustc

governance-team-wg-polonius-name = Polonius working group
governance-team-wg-polonius-description = Working on an experimental new borrow-checker implementation

governance-team-wg-polymorphization-name = Polymorphization working group
governance-team-wg-polymorphization-description = Implementing polymorphization to reduce unnecessary monomorphisation in rustc

governance-team-wg-prioritization-name = Prioritization working group
governance-team-wg-prioritization-description = Triaging bugs, mainly deciding if bugs are critical (potential release blockers) or not

governance-team-wg-rfc-2229-name = RFC 2229 working group
governance-team-wg-rfc-2229-description = Improving the behavior of closure-capture, and improving the documentation on closures

governance-team-wg-rust-by-example-name = Rust by Example working group
governance-team-wg-rust-by-example-description = Maintaining and updating the official Rust by Example book

governance-team-wg-rustc-dev-guide-name = Rustc Dev Guide working group
governance-team-wg-rustc-dev-guide-description = Making the compiler easier to learn by maintaining and improving the Rustc Dev Guide

governance-team-wg-rustc-reading-club-name = Rust Code Reading Club working group
governance-team-wg-rustc-reading-club-description = Helping new and experienced contributors learn more about rustc

governance-team-wg-rustfix-name = Rustfix working group
governance-team-wg-rustfix-description = Developing cargo-fix and serving as a point of contact for other teams

governance-team-wg-safe-transmute-name = safe-transmute project group
governance-team-wg-safe-transmute-description = A working-group project to extend the Rust language to support safe transmute between types

governance-team-wg-secure-code-name = Secure Code working group
governance-team-wg-secure-code-description = Making it easy to write secure code in Rust

governance-team-wg-security-response-name = Security Response WG
governance-team-wg-security-response-description = Triaging and responding to incoming vulnerability reports

governance-team-wg-self-profile-name = Self-profile working group
governance-team-wg-self-profile-description = Improving the -Z self-profile feature of the Rust compiler

governance-team-wg-triage-name = Triage working group
governance-team-wg-triage-description = Triaging repositories under the rust-lang organisation

governance-team-wg-wasm-name = WebAssembly (WASM) working group
governance-team-wg-wasm-description = Improving on the end-to-end experience of embedding Rust code in JS libraries and apps via WebAssembly
